### ISSUE TITLE
On pc screens with different resolutions it is difficult to read

### ISSUE THREAD

**Issue by AlePaff** [FdelMazo/figure-610#1]
As you can see in the gif, in the side part with the description it's not possible to scroll down to continue reading, so you have to resort to "tricks" like keeping right click or go to the "inspect element" part and read from there the text or moving the page far enough so that the scroll bar disappears but in that case you are not able to read it.
![ddddd](https://user-images.githubusercontent.com/43119891/155937879-045634c2-8d6d-47c7-bb0d-b1b7ca2a109d.gif)

ps: I loved the tool and it helped me to understand several concepts with way more perspective

**Comment by FdelMazo** [comment]
Magnifico che! Liquido los finales y me pongo a solucionarlo! O bienvenido seas si se te ocurre alguna solucion (pense que tal vez solamente clickear te pinee el texto?) y queres programarla o al menos diseñarla y contarmela para que yo la implemente!

**Comment by FdelMazo** [comment]
Sabes que en su momento me lo cruce y mi solucion fue.... chotisima.

Si te paras en el CBL (o en cualquier texto muy largo), y usas las flechitas del teclado, el texto scrollea.... voy a ver si se me ocurre algo un poco menos choto

**Comment by FdelMazo** [comment]
Bueno, quick fix, si te parece más o menos aceptable, chifla y hago el commit y cierro el issue.

Básicamente, si el texto es muy largo... te aparece un subtitulo que dice `Use the UP and DOWN arrows to scroll`

Choto, hacky, pero creo que soluciona un poco

![image](https://user-images.githubusercontent.com/25667102/155993037-5d838781-799c-4ab1-9d8a-34bf128038c8.png)

**Comment by AlePaff** [comment]
uhh buenisimo, no conocía esa jaja, dale, a mi me parece bien. Eso si, tengo que seleccionar una parte del texto y recién ahi me deja scrollear para abajo.
Lo de clickear y que quede pineado me parece mejor ajaj, la verdad me encantaría aportar, pero por el momento se poco y nada de javascript. Abrazo

**Comment by FdelMazo** [comment]
> tengo que seleccionar una parte del texto y recién ahi me deja scrollear para abajo.

Solucionado! En chrome había un problema con el `.focus()` --> https://stackoverflow.com/a/59947693
